backend:
  name: git-gateway
  branch: main # Change to 'master' if your repo uses master

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image"}
      - {label: "Read Time", name: "readTime", widget: "string", default: "5 min read"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Short Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}